version: '3.9'

services:
    app:
        build: .
        environment:
            NODE_ENV: production
        ports:
            - '4200:4200'
            - '3000:3000'
        volumes:
            - ./data:/opt/app/data
        restart: always
